// frontend/src/pages/admins/AdminsPage.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Button,
  Card,
  Checkbox,
  Col,
  ConfigProvider,
  Form,
  Input,
  Layout,
  Modal,
  Row,
  Space,
  Spin,
  Table,
  Tag,
  message,
} from 'antd';
import { DeleteOutlined, EditOutlined, PlusOutlined, TeamOutlined } from '@ant-design/icons';

import { useTheme } from '@/hooks/useTheme';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import { HttpUtil } from '@/utils';
import AppSidebar from '@/components/AppSidebar';
import '@/styles/page-cards.css';

const basePath = window.X_UI_BASE_PATH || '';
const requestUri = window.location.pathname;

interface SubAdmin {
  id: number;
  username: string;
  role: string;
  allowedInbounds: number[];
}

interface InboundOption {
  id: number;
  remark: string;
  port: number;
  protocol: string;
}

interface AdminFormValues {
  username: string;
  password: string;
  allowedInbounds: number[];
}

const EMPTY_FORM: AdminFormValues = {
  username: '',
  password: '',
  allowedInbounds: [],
};

export default function AdminsPage() {
  const { t } = useTranslation();
  const { isDark, isUltra, antdThemeConfig } = useTheme();
  const { isMobile } = useMediaQuery();
  const [modal, modalContextHolder] = Modal.useModal();
  const [messageApi, messageContextHolder] = message.useMessage();

  const [admins, setAdmins] = useState<SubAdmin[]>([]);
  const [inbounds, setInbounds] = useState<InboundOption[]>([]);
  const [fetched, setFetched] = useState(false);

  const [formOpen, setFormOpen] = useState(false);
  const [formMode, setFormMode] = useState<'add' | 'edit'>('add');
  const [editingId, setEditingId] = useState<number | null>(null);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<AdminFormValues>(EMPTY_FORM);

  const fetchData = useCallback(async () => {
    const [adminsRes, inboundsRes] = await Promise.all([
        HttpUtil.get('/panel/api/admins', undefined, { silent: true }),
        HttpUtil.get('/panel/api/inbounds/list', undefined, { silent: true }),
    ]);
    if (adminsRes?.success) {
      setAdmins(
        (adminsRes.obj as SubAdmin[]).map((a) => ({
          ...a,
          allowedInbounds: Array.isArray(a.allowedInbounds) ? a.allowedInbounds : [],
        })),
      );
    }
    if (inboundsRes?.success) {
      setInbounds(
        (inboundsRes.obj as InboundOption[]).map((ib) => ({
          id: ib.id,
          remark: ib.remark,
          port: ib.port,
          protocol: ib.protocol,
        })),
      );
    }
    setFetched(true);
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  const openAdd = useCallback(() => {
    setFormMode('add');
    setEditingId(null);
    setForm(EMPTY_FORM);
    setFormOpen(true);
  }, []);

  const openEdit = useCallback((admin: SubAdmin) => {
    setFormMode('edit');
    setEditingId(admin.id);
    setForm({ username: admin.username, password: '', allowedInbounds: admin.allowedInbounds });
    setFormOpen(true);
  }, []);

  const confirmDelete = useCallback((admin: SubAdmin) => {
    modal.confirm({
      title: t('pages.admins.deleteConfirmTitle', { username: admin.username }),
      content: t('pages.admins.deleteConfirmContent'),
      okText: t('delete'),
      okType: 'danger',
      cancelText: t('cancel'),
      onOk: async () => {
        const res = await HttpUtil.post(`/panel/api/admins/delete/${admin.id}`);
        if (res?.success) {
          messageApi.success(t('pages.admins.toasts.deleted'));
          fetchData();
        }
      },
    });
  }, [modal, t, messageApi, fetchData]);

  const onSave = useCallback(async () => {
    if (!form.username.trim()) {
      messageApi.error(t('pages.admins.toasts.usernameRequired'));
      return;
    }
    if (formMode === 'add' && !form.password.trim()) {
      messageApi.error(t('pages.admins.toasts.passwordRequired'));
      return;
    }
    setSaving(true);
    const payload = {
      username: form.username.trim(),
      password: form.password,
      allowedInbounds: form.allowedInbounds,
    };
    const url = formMode === 'add'
      ? '/panel/api/admins/create'
      : `/panel/api/admins/update/${editingId}`;
    const res = await HttpUtil.post(url, payload);
    setSaving(false);
    if (res?.success) {
      messageApi.success(
        formMode === 'add' ? t('pages.admins.toasts.created') : t('pages.admins.toasts.updated'),
      );
      setFormOpen(false);
      fetchData();
    }
  }, [form, formMode, editingId, messageApi, t, fetchData]);

  const inboundLabel = useCallback((ib: InboundOption) =>
    `${ib.remark || ib.protocol} :${ib.port}`,
  []);

  const columns = useMemo(() => [
    {
      title: t('pages.admins.username'),
      dataIndex: 'username',
      key: 'username',
      render: (val: string) => <strong>{val}</strong>,
    },
    {
      title: t('pages.admins.access'),
      key: 'access',
      render: (_: unknown, record: SubAdmin) => {
        if (record.allowedInbounds.length === 0) {
          return <Tag color="green">{t('pages.admins.fullAccess')}</Tag>;
        }
        return (
          <Space wrap size={4}>
            {record.allowedInbounds.map((id) => {
              const ib = inbounds.find((i) => i.id === id);
              return (
                <Tag key={id} color="blue">
                  {ib ? inboundLabel(ib) : `#${id}`}
                </Tag>
              );
            })}
          </Space>
        );
      },
    },
    {
      title: t('action'),
      key: 'action',
      width: 100,
      render: (_: unknown, record: SubAdmin) => (
        <Space>
          <Button
            size="small"
            icon={<EditOutlined />}
            onClick={() => openEdit(record)}
          />
          <Button
            size="small"
            danger
            icon={<DeleteOutlined />}
            onClick={() => confirmDelete(record)}
          />
        </Space>
      ),
    },
  ], [t, inbounds, inboundLabel, openEdit, confirmDelete]);

  const pageClass = useMemo(() => {
    const parts = ['admins-page'];
    if (isDark) parts.push('is-dark');
    if (isUltra) parts.push('is-ultra');
    return parts.join(' ');
  }, [isDark, isUltra]);

  return (
    <ConfigProvider theme={antdThemeConfig}>
      {messageContextHolder}
      {modalContextHolder}
      <Layout className={pageClass}>
        <AppSidebar basePath={basePath} requestUri={requestUri} />

        <Layout className="content-shell">
          <Layout.Content id="content-layout" className="content-area">
            <Spin spinning={!fetched} delay={200} size="large">
              {!fetched ? (
                <div className="loading-spacer" />
              ) : (
                <Row gutter={[isMobile ? 8 : 16, isMobile ? 8 : 12]}>
                  <Col span={24}>
                    <Card
                      hoverable
                      title={
                        <Space>
                          <TeamOutlined />
                          {t('pages.admins.title')}
                        </Space>
                      }
                      extra={
                        <Button type="primary" icon={<PlusOutlined />} onClick={openAdd}>
                          {!isMobile && t('pages.admins.addAdmin')}
                        </Button>
                      }
                    >
                      <Table
                        dataSource={admins}
                        columns={columns}
                        rowKey="id"
                        pagination={false}
                        size="small"
                      />
                    </Card>
                  </Col>
                </Row>
              )}
            </Spin>
          </Layout.Content>
        </Layout>
      </Layout>

      <Modal
        open={formOpen}
        title={formMode === 'add' ? t('pages.admins.addAdmin') : t('pages.admins.editAdmin')}
        okText={t('save')}
        cancelText={t('cancel')}
        confirmLoading={saving}
        onOk={onSave}
        onCancel={() => setFormOpen(false)}
        destroyOnHidden
      >
        <Form layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item label={t('pages.admins.username')} required>
            <Input
              value={form.username}
              onChange={(e) => setForm((f) => ({ ...f, username: e.target.value }))}
              autoComplete="off"
            />
          </Form.Item>

          <Form.Item
            label={t('pages.admins.password')}
            extra={formMode === 'edit' ? t('pages.admins.passwordHint') : undefined}
            required={formMode === 'add'}
          >
            <Input.Password
              value={form.password}
              onChange={(e) => setForm((f) => ({ ...f, password: e.target.value }))}
              autoComplete="new-password"
            />
          </Form.Item>

          <Form.Item
            label={t('pages.admins.allowedInbounds')}
            extra={t('pages.admins.allowedInboundsHint')}
          >
            <Checkbox.Group
              value={form.allowedInbounds}
              onChange={(vals) => setForm((f) => ({ ...f, allowedInbounds: vals as number[] }))}
              style={{ display: 'flex', flexDirection: 'column', gap: 6 }}
            >
              {inbounds.map((ib) => (
                <Checkbox key={ib.id} value={ib.id}>
                  {inboundLabel(ib)}
                </Checkbox>
              ))}
            </Checkbox.Group>
          </Form.Item>
        </Form>
      </Modal>
    </ConfigProvider>
  );
}

// frontend/src/pages/admins/AdminsPage.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SafetyOutlined,
} from '@ant-design/icons-vue';
import { message, Modal } from 'ant-design-vue';
import AppSidebar from '@/components/AppSidebar.vue';
import { HttpUtil } from '@/utils';
import { antdThemeConfig, theme } from '@/composables/useTheme.js';

const { t } = useI18n();

const basePath = window.X_UI_BASE_PATH ?? '/';
const requestUri = window.location.pathname;

const admins = ref([]);
const inboundOptions = ref([]);
const loading = ref(false);
const modalOpen = ref(false);
const saving = ref(false);
const isEdit = ref(false);
const editingId = ref(null);

const form = ref({
  username: '',
  password: '',
  confirmPassword: '',
  allowedInbounds: [],
});

const columns = [
  { title: '#', dataIndex: 'id', width: 60 },
  { title: t('username'), dataIndex: 'username' },
  { title: t('pages.admins.allowedInbounds'), key: 'allowedInbounds' },
  { title: t('pages.admins.actions'), key: 'actions', width: 120, align: 'center' },
];

function parseAllowedIds(admin) {
  if (!admin.allowedInbounds) return [];
  if (Array.isArray(admin.allowedInbounds)) return admin.allowedInbounds;
  try { return JSON.parse(admin.allowedInbounds); } catch { return []; }
}

function inboundLabel(id) {
  const opt = inboundOptions.value.find((o) => o.id === id);
  return opt ? `${opt.remark || opt.protocol}:${opt.port}` : `#${id}`;
}

async function fetchAdmins() {panel/api/admins`);
  loading.value = true;
  try {
    const msg = await HttpUtil.get(`${basePath}panel/api/admins`);
    if (msg?.success) admins.value = msg.obj ?? [];
  } finally {
    loading.value = false;
  }
}

async function fetchInbounds() {
  const msg = await HttpUtil.get(`${basePath}panel/api/inbounds/options`);
  if (msg?.success) inboundOptions.value = msg.obj ?? [];
}

function openCreate() {
  isEdit.value = false;
  editingId.value = null;
  form.value = { username: '', password: '', confirmPassword: '', allowedInbounds: [] };
  modalOpen.value = true;
}

function openEdit(admin) {
  isEdit.value = true;
  editingId.value = admin.id;
  form.value = {
    username: admin.username,
    password: '',
    confirmPassword: '',
    allowedInbounds: parseAllowedIds(admin),
  };
  modalOpen.value = true;
}

async function save() {
  if (!form.value.username) {
    message.error(t('pages.login.toasts.emptyUsername'));
    return;
  }
  if (!isEdit.value && !form.value.password) {
    message.error(t('pages.login.toasts.emptyPassword'));
    return;
  }
  if (form.value.password && form.value.password !== form.value.confirmPassword) {
    message.error(t('pages.admins.passwordMismatch'));
    return;
  }
  saving.value = true;
  try {
    const payload = {
      username: form.value.username,
      password: form.value.password,
      allowedInbounds: form.value.allowedInbounds,
    };
    const msg = isEdit.value
      ? await HttpUtil.put(`${basePath}panel/api/admins/${editingId.value}`, payload)
      : await HttpUtil.post(`${basePath}panel/api/admins`, payload);
    if (msg?.success) {
      modalOpen.value = false;
      await fetchAdmins();
    }
  } finally {
    saving.value = false;
  }
}

function confirmDelete(admin) {
  Modal.confirm({
    title: t('pages.admins.deleteTitle'),
    content: t('pages.admins.deleteContent', { username: admin.username }),
    okType: 'danger',
    onOk: () => doDelete(admin.id),
  });
}

async function doDelete(id) {
  const msg = await HttpUtil.delete(`${basePath}panel/api/admins/${id}`);
  if (msg?.success) await fetchAdmins();
}

onMounted(async () => {
  await Promise.all([fetchAdmins(), fetchInbounds()]);
});
</script>

<template>
  <a-config-provider :theme="antdThemeConfig">
    <a-layout :class="{ 'is-dark': theme.isDark }" style="min-height: 100vh">
      <AppSidebar :base-path="basePath" :request-uri="requestUri" />
      <a-layout-content style="padding: 24px">

        <div style="display:flex; align-items:center; justify-content:space-between; margin-bottom:16px">
          <h2 style="margin:0; display:flex; align-items:center; gap:8px">
            <SafetyOutlined />
            {{ t('menu.admins') }}
          </h2>
          <a-button type="primary" @click="openCreate">
            <template #icon><PlusOutlined /></template>
            {{ t('pages.admins.addAdmin') }}
          </a-button>
        </div>

        <a-table
          :columns="columns"
          :data-source="admins"
          :loading="loading"
          row-key="id"
          :pagination="false"
          bordered
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'allowedInbounds'">
              <a-tag v-if="!parseAllowedIds(record).length" color="warning">
                {{ t('pages.admins.noInbounds') }}
              </a-tag>
              <template v-else>
                <a-tag
                  v-for="id in parseAllowedIds(record)"
                  :key="id"
                  color="blue"
                  style="margin-bottom:2px"
                >
                  {{ inboundLabel(id) }}
                </a-tag>
              </template>
            </template>

            <template v-else-if="column.key === 'actions'">
              <a-space>
                <a-tooltip :title="t('edit')">
                  <a-button size="small" @click="openEdit(record)">
                    <template #icon><EditOutlined /></template>
                  </a-button>
                </a-tooltip>
                <a-tooltip :title="t('delete')">
                  <a-button size="small" danger @click="confirmDelete(record)">
                    <template #icon><DeleteOutlined /></template>
                  </a-button>
                </a-tooltip>
              </a-space>
            </template>
          </template>
        </a-table>

      </a-layout-content>
    </a-layout>

    <!-- Create / Edit modal -->
    <a-modal
      v-model:open="modalOpen"
      :title="isEdit ? t('pages.admins.editAdmin') : t('pages.admins.addAdmin')"
      :ok-text="t('save')"
      :confirm-loading="saving"
      :destroy-on-close="true"
      @ok="save"
    >
      <a-form layout="vertical" style="margin-top:8px">
        <a-form-item :label="t('username')">
          <a-input v-model:value="form.username" :placeholder="t('username')" />
        </a-form-item>

        <a-form-item :label="t('password')">
          <a-input-password
            v-model:value="form.password"
            :placeholder="isEdit ? t('pages.admins.leaveBlankToKeep') : t('password')"
          />
        </a-form-item>

        <a-form-item :label="t('pages.admins.confirmPassword')">
          <a-input-password
            v-model:value="form.confirmPassword"
            :placeholder="t('pages.admins.confirmPassword')"
          />
        </a-form-item>

        <a-form-item :label="t('pages.admins.allowedInbounds')">
          <a-select
            v-model:value="form.allowedInbounds"
            mode="multiple"
            :placeholder="t('pages.admins.selectInbounds')"
            :options="inboundOptions.map((o) => ({
              value: o.id,
              label: `${o.remark || o.protocol}:${o.port}`,
            }))"
            style="width:100%"
          />
          <div style="margin-top:4px; opacity:0.65; font-size:12px">
            {{ t('pages.admins.inboundsHint') }}
          </div>
        </a-form-item>
      </a-form>
    </a-modal>
  </a-config-provider>
</template>
